# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cae1fd115d70c78acb4282ce25ffd07b9227ee3c96c89508b25f797ffe638e95d9da89894603745ca9f26c4c93483889fd902b3d7c4b6033c90c8b9bd4e16a88

test:
  secret_key_base: de4a88fecc0af0ae9f6dd60ecc151ad14accc9851e0ff5564a0ac4f1579a42428ee66fa23560eacf0ba1a6e311c74ac4bf7a2133f30aad563c4f97d02c75a34c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
